# Community.create(name: 'Java')
# Community.create(name: 'Ruby')
# Community.create(name: 'VueJs')
# Community.create(name: 'Python')
# Community.create(name: 'Go Lang')
# Community.create(name: '.Net')
